---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible -qq

script:
  # Test for Syntax
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --syntax-check
  # Test for Failure
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --connection=local
    --become
  # Test for Idempotence
  - >
    ansible-playbook -i tests/inventory tests/test.yml
    --connection=local
    --become
    | grep -q 'changed=0.*failed=0'
  # Test for Success
  - >
    getent passwd $USER | grep -q '/usr/bin/zsh'
  - >
    zsh --version > /dev/null
