---
# tasks file for debian

- name: "Install ZSH"
  become: yes
  apt:
      name: "{{ item }}"
      state: present
      update-cache: yes
      cache_valid_time: 3600
  with_items:
    - zsh
    - git
  tags:
    - dependency
