---
# tasks file for install

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Clone oh-my-zsh"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ oh_my_zsh_user_home }}/.oh-my-zsh"
  tags:
    - install

- name: "Create new zshrc"
  copy:
    src: "{{ oh_my_zsh_user_home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ oh_my_zsh_user_home }}/.zshrc"
    remote_src: yes
  tags:
    - configure

- name: "Switch to shell to zsh"
  user:
    name: "{{ oh_my_zsh_user }}"
    shell: /usr/bin/zsh
  become: yes
  tags:
    - configure
