---
# tasks file for install

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: "Clone oh-my-zsh"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ oh_my_zsh_user_home }}/.oh-my-zsh"

- name: "Create new zshrc"
  copy:
    src: "{{ oh_my_zsh_user_home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ oh_my_zsh_user_home }}/.zshrc"
    remote_src: yes

- name: use specific theme
  template:
    src: theme.zsh.j2
    dest: "{{ oh_my_zsh_user_home }}/.oh-my-zsh/custom/theme.zsh"
  when: oh_my_zsh_theme is defined

- name: "Switch to shell to zsh"
- name: place aliases
  template:
    src: aliases.zsh.j2
    dest: "{{ oh_my_zsh_user_home }}/.oh-my-zsh/custom/aliases.zsh"
  when: oh_my_zsh_aliases is defined

- name: "Switch shell to zsh"
  user:
    name: "{{ oh_my_zsh_user }}"
    shell: /usr/bin/zsh
    append: yes
  become: yes
