---
# tasks file for install

- include: debian.yml
  when:
    ansible_os_family: 'Debian'

- name: "Install oh-my-zsh"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ oh_my_zsh_user_home }}/.oh-my-zsh"

- name: "Create new zshrc"
  copy:
    src: "{{ oh_my_zsh_user_home }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ oh_my_zsh_user_home }}/.zshrc"

- name: "Switch to shell to zsh"
  user:
    name: "{{ oh_my_zsh_user }}"
    shell: /bin/zsh
  sudo: yes
